### ISSUE TITLE
no php5 5.6.16 for jessie

### ISSUE THREAD

**Issue by divinity76** [gplessis/dotdeb-php#108]
jessie's php5 is frozen on 5.6.14, (and i recently encountered a segfault which was fixed in 5.6.15,) and debian jessie has no intentions of upgrading to newer php - merely backport security fixes.. can we get a jessie-php56 repo, like wheezy-php56 ? (wheezy's already got php 5.6.16)

**Comment by gplessis** [comment]
Jessie already provides PHP 5.6 and it is upgraded every time security issue are discovered (see the occurrences of jessie-security on [this page](https://packages.qa.debian.org/p/php5.html)). I won't duplicate the effort, sorry.

**Comment by Talkless** [comment]
@gplessis I am are currently using php 5.4 packages on Wheezy, because it fixes libgd image antialiasing issue [1], as it's apparently compiled with PHP libgd, not upstream one that Debian uses, and very very thanks for that.

It would be very useful to have 5.6 in Dotdeb repository in that regard. Otherwise, Debian is useless if one needs to render images with PHP and gd.
 
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778596
