### ISSUE TITLE
Wrong package dependency for some php7.0 packages

### ISSUE THREAD

**Issue by MarcinOrlowski** [gplessis/dotdeb-php#150]
Hi,

I found that when I try to install PHP7 from packages named with `php7.0-*` I still will end up having `php-common` installed, despite `php7.0-common` being there as well. I find this a bit odd as to my understanding the whole point of having packages named `php7.0-*` is to avoid package collisions but this issue perfectly kills the whole purpose?

**Comment by gplessis** [comment]
The idea behind this is to have multiple PHP versions installed on a machine : 
* `php-*` package would contain everything common to all the versions or would be meta-packages with dependencies on the multiple corresponding `phpx.y-*` packages.
* `phpx.y-*` packages would be specific to only one PHP version.

It's already the case in Stretch/Sid, but because I didn't want to maintain the PHP 5.6 branch for Jessie, it looks confusing, I can admit that. It will make sense once PHP 7.1 is out :)
