### ISSUE TITLE
igbinary support

### ISSUE THREAD

**Issue by sandermarechal** [gplessis/dotdeb-php#19]
Please package the PECL igbinary extension and compile php5-redis to support igbinary.

Doctrine2 ORM has support for metadata caching in Redis, but it assumes igbinary support is enabled. This causes a fatal error when using it together with the dotdeb version of php5-redis because of an undefined constant. I have reported this as a bug at Doctrine, but this does not help when using existing Doctrine versions.

Adding igbinary support to dotdeb would allow existing versions of Doctrine to use Redis for caching as well.

**Comment by rlex** [comment]
Any news on that one?

**Comment by joeyhub** [comment]
I use my own package for igbinary. There's something to watch out for though in the build environment.

You'll need a devel package for igbinary or if you're lazy just make sure igbinary is built first and the build dir is still around. This is because packages like php5-redis need igbinary.h and the lib for linking with that option enabled.

**Comment by gplessis** [comment]
igbinary support is available with <tt>php7.0-igbinary</tt>. It has also been enabled in <tt>php7.0-memcached</tt> and <tt>php7.0-redis</tt>.
